### ISSUE TITLE
The Blank Could Not Be Identified In Absolute Path?

### ISSUE THREAD

**Issue by sunnyccshine** [dss-extensions/dss_python#48]
It seems that the blank could not be identified in the absolute path.

My code is the following:
    dss_engine = dss.DSS
    dss_engine.Text.Command = "compile D:\OneDrive - zju.edu.cn\pythoncodes\plf_ieee33_bus-master\ieee34.dss"

The following error occurs when running: 
Traceback (most recent call last):
  File "D:/OneDrive - zju.edu.cn/pythoncodes/plf_ieee33_bus-master/ceshi.py", line 43, in <module>
    ceshi2()
  File "D:/OneDrive - zju.edu.cn/pythoncodes/plf_ieee33_bus-master/ceshi.py", line 9, in ceshi2
    dss_engine.Text.Command = "compile D:\OneDrive - zju.edu.cn\pythoncodes\plf_ieee33_bus-master\ieee34.dss"
  File "D:\Program Files\Python\Python37-32\lib\site-packages\dss\dss_capi_gr\IText.py", line 22, in Command
    self.CheckForError(self._lib.Text_Set_Command(Value))
  File "D:\Program Files\Python\Python37-32\lib\site-packages\dss\_cffi_api_util.py", line 128, in _check_for_error
    raise DSSException(error_num, self._get_string(self._lib.Error_Get_Description()))
dss._cffi_api_util.DSSException: (#242) Redirect file not found: "D:\OneDrive"

**Comment by sunnyccshine** [comment]
Thank you for your advice and guidance. It wonderfully solved my problem.
